name: Python CI

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout rep
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        
    - name: ls
      shell: bash
      run: ls
      working-directory: .
      
    - name: Style check
      run: flake8 src
      working-directory: .

    - name: Run tests
      run: pytest tests
      working-directory: .
